name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # 匹配版本号格式，如 v1.0.0, v0.2.0 等
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # 先只打包 windows 版本
        # os: [windows-latest, macos-latest, ubuntu-latest]
        os: [windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm i
        
      - name: Build and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish